### ISSUE TITLE
OCR workflow on macOS 12 no result with unavailable model

### ISSUE THREAD

**Issue by Schullinger** [zeitlings/alfred-workflows#11]
Thanks for the workflow.
After installing it, it doesn't do anything except for giving me notice saying "Copied Recognized Text".
What am I doing wrong. 
Everything seems to be installed properly.
I'am using mac os 12, having it as well set up in the configuration of the workflow.
Is there anything I'am missing?

**Comment by zeitlings** [comment]
Hey @Schullinger, you're referring to either the OCR light or OCR+ workflow. If it's the former, your configuration will look a little different. However, since you are running macOS 12, make sure you select the appropriate model version in the configuration. Version 2 should work in your case, but alas, depending on your target language, you might get disappointing results. In my experience, Apple's Vision framework does not produce satisfactory results until v3.

<img width="644" alt="Screenshot 2024-04-03 at 21 12 22" src="https://github.com/zeitlings/alfred-workflows/assets/25689591/3223cf06-8747-460d-b839-97da0a096cfd">
