### ISSUE TITLE
[OCR+ bug] Workflow run immediately every when do not enter after input keyword.

### ISSUE THREAD

**Issue by chumido** [zeitlings/alfred-workflows#3]
As title, 

When i input the keyword, workflow run immediately. When i open alfred, because the keyword still there, then the workflow keep running. i have to turn off workflow, and open alfred to delete keyword. Can you please check. Thank you very much.

https://user-images.githubusercontent.com/129524162/230563110-04f4142a-0283-42e5-80c1-f784f1e32cb0.mp4

**Comment by zeitlings** [comment]
Hey, I'm not sure I understand the scenario you're describing. I cannot reproduce the behavior from your video. How do you launch Alfred after enabling the OCR workflow: using the default shortcut, a custom shortcut, the OCR workflow shortcut (`cmd+shift+6`)? 

What I think I can gather from the end of the video is that for each time you call the workflow again using the _`ocr` keyword_[^1], the workflow runs again. Each of these activations of the workflow runs sequentially and has then to be dismissed one by one. I should have a fix for this.

The output of the **debug panel** might also be helpful, i.e. open the workflow in Alfred and enable it via `cmd+D`. 

[^1]: How though? The screen or keyboard input should be locked while in snapshot mode, that is, navigating through the Alfred history using the arrow keys or `ctrl+p` / `ctrl+n` should not work.

**Comment by chumido** [comment]
This is my step:
1. Open alfred
2. I just finish keyword "ocr"
3. The workflow run immediately (keyword "ocr" still in alfred)
4. So every time i open alfred, the workflow run immediately (i can't delete keyword to stop)
5. I need to open Alfred Pref and disable the workflow to stop alfred trigger workflow because keyword still in alfred

This is step by step video and debug panel:
https://user-images.githubusercontent.com/129524162/230620956-9c2c4f42-3b85-4959-99b5-93580f85668f.mp4

**Comment by zeitlings** [comment]
Thanks for the video! I am not sure exactly what is causing this behavior, but have you [updated the workflow yet](https://github.com/zeitlings/alfred-workflows/releases/tag/v1.2.3-ocr2)? The update fixes an issue that may or may not be the cause of the problem, and also tweaks some concurrency settings. Let me know if the weird behavior persists in the latest version.

**Comment by chumido** [comment]
i installed new version 1.2.3. But it still happen 😅

**Comment by zeitlings** [comment]
I noticed something strange in your videos. When you launch Alfred, do you always launch it with the last keyword you entered, or in other words, the last workflow you used? That's not standard behavior. That the snapshot mode is immediately activated when you type the keyword `ocr` __is intentional.__ If you start Alfred with the previous keyword, you will indeed be stuck in a loop. But that is by design then 😄.

Perhaps you can try to change the startup behavior of the workflow to suit your use case, but other than that there is little I can do if my assumption about Alfred starting with the last used workflow is correct. If you still want to use the workflow in this case, I suggest using only the shortcut and the Universal Action, and completely disabling the script filter (which is mainly intended for progress tracking).

![script-filter-change](https://user-images.githubusercontent.com/25689591/230718083-bef77b36-5efc-4651-90ea-5cf39271e200.jpg)

**Comment by chumido** [comment]
Thank you very much. Seem like i will use it that way 😅
